# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2020-04-27 20:43
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('music', '0002_auto_20200427_2037'),
    ]

    operations = [
        migrations.AddField(
            model_name='album',
            name='date',
            field=models.DateField(default=datetime.datetime.now),
        ),
    ]
