# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2020-04-28 22:09
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('music', '0004_auto_20200428_2158'),
    ]

    operations = [
        migrations.RenameField(
            model_name='album',
            old_name='artist',
            new_name='actor',
        ),
        migrations.RenameField(
            model_name='album',
            old_name='artist1',
            new_name='actor2',
        ),
        migrations.RenameField(
            model_name='album',
            old_name='album_logo',
            new_name='movie_logo',
        ),
        migrations.RenameField(
            model_name='album',
            old_name='album_title',
            new_name='movie_title',
        ),
        migrations.RenameField(
            model_name='album',
            old_name='is_favorite',
            new_name='new',
        ),
    ]
